### ISSUE TITLE
How notify an event

### ISSUE THREAD

**Issue by m1rku5** [elpheria/rpc-websockets#111]
Hi,
I've created an event on my server called 'test'. Then I want notify on this event from a client, but I got this error:
```
D:\Test\JS\ms-proxy\node_modules\rpc-websockets\dist\lib\client.js:251
        if (!_this3.ready) return reject(new Error("socket not ready"));
                                         ^

Error: socket not ready
    at D:\Test\JS\ms-proxy\node_modules\rpc-websockets\dist\lib\client.js:251:42
    at new Promise (<anonymous>)
    at Client.notify (D:\Test\JS\ms-proxy\node_modules\rpc-websockets\dist\lib\client.js:250:14)
    at Timeout._onTimeout (D:\Test\JS\ms-proxy\ws_client.js:63:16)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

The code of my client is the following:
```
function send_test_event(resolve)
{
   let ws = new WebSocket(server_addr);

   ws.on('open', () => {
      let name = 'test';

      let i = 0;
      for(i = 0; i < 1; ++ i) {
         setTimeout(() => {
            console.log('i: ', i);
            ws.notify(name, { event: 'event' });
         }, 1000);
      }

      ws.close();
   });
}

send_rebound_event(console.log);
```
On the server is online and the event has been already created:
```
Events:  [ 'test' ]
```
Where's my error?

Thanks,
   Mirko

**Comment by mkozjak** [comment]
You called `ws.close()` instantly on running `send_test_event`. Node.js is async. `for` and `ws.close` happen at practically the same time.

**Comment by m1rku5** [comment]
You're right...

Thanks
   Mirko
