### ISSUE TITLE
esnext problem

### ISSUE THREAD

**Issue by basz** [elpheria/rpc-websockets#160]
the changed esnext compile thing from 1.11.0 is breaking usage for me in an EmberJS app

```
websocket.browser.js:75 Uncaught (in promise) ReferenceError: exports is not defined
    at eval (websocket.browser.js:75:1)
    at ../../../../../node_modules/.pnpm/rpc-websockets@7.11.0/node_modules/rpc-websockets/dist/lib/client/websocket.browser.js (chunk.8496e8a15f9678fec839.js:14589:1)
    at __webpack_require__ (chunk.3416202bc0ec78d6e0f4.js:31:42)
    at eval (index.browser.js:12:45)
    at ../../../../../node_modules/.pnpm/rpc-websockets@7.11.0/node_modules/rpc-websockets/dist/index.browser.js (chunk.8496e8a15f9678fec839.js:14567:1)
    at __webpack_require__ (chunk.3416202bc0ec78d6e0f4.js:31:42)
    at eval (socket.actions.js:8:26)
    at ../../../../../packages/@3dlayermaker-common/dist/moonraker/socket.actions.js (chunk.17f662c24397a7eb1ab4.js:1567:1)
    at __webpack_require__ (chunk.3416202bc0ec78d6e0f4.js:31:42)
    at eval (index.js:26:14)
```

That [file](https://github.com/elpheria/rpc-websockets/blob/trunk/dist/lib/client/websocket.browser.js) ends up as (indeed without `exports`)

```
Object.defineProperty(__webpack_exports__, "__esModule", ({
  value: true
}));
const eventemitter3_1 = __webpack_require__(/*! eventemitter3 */ "../../../../../node_modules/.pnpm/eventemitter3@4.0.7/node_modules/eventemitter3/index.js");
class WebSocketBrowserImpl extends eventemitter3_1.EventEmitter {
  /** Instantiate a WebSocket class
   * @constructor
   * @param {String} address - url to a websocket server
   * @param {(Object)} options - websocket options
   * @param {(String|Array)} protocols - a list of protocols
   * @return {WebSocketBrowserImpl} - returns a WebSocket instance
   */
  constructor(address, options, protocols) {
    super();
    (0,_Users_bas_Documents_Projects_iSole3D_3DLayerMaker_repositories_3DLayerMaker_Dashboard_node_modules_pnpm_babel_runtime_7_23_9_node_modules_babel_runtime_helpers_esm_defineProperty_js__WEBPACK_IMPORTED_MODULE_0__["default"])(this, "socket", void 0);
    this.socket = new window.WebSocket(address, protocols);
    this.socket.onopen = () => this.emit("open");
    this.socket.onmessage = event => this.emit("message", event.data);
    this.socket.onerror = error => this.emit("error", error);
    this.socket.onclose = event => {
      this.emit("close", event.code, event.reason);
    };
  }
  /**
   * Sends data through a websocket connection
   * @method
   * @param {(String|Object)} data - data to be sent via websocket
   * @param {Object} optionsOrCallback - ws options
   * @param {Function} callback - a callback called once the data is sent
   * @return {Undefined}
   */
  send(data, optionsOrCallback, callback) {
    const cb = callback || optionsOrCallback;
    try {
      this.socket.send(data);
      cb();
    } catch (error) {
      cb(error);
    }
  }
  /**
   * Closes an underlying socket
   * @method
   * @param {Number} code - status code explaining why the connection is being closed
   * @param {String} reason - a description why the connection is closing
   * @return {Undefined}
   * @throws {Error}
   */
  close(code, reason) {
    this.socket.close(code, reason);
  }
  addEventListener(type, listener, options) {
    this.socket.addEventListener(type, listener, options);
  }
}
/**
 * factory method for common WebSocket instance
 * @method
 * @param {String} address - url to a websocket server
 * @param {(Object)} options - websocket options
 * @return {Undefined}
 */
function default_1(address, options) {
  return new WebSocketBrowserImpl(address, options);
}
exports.default = default_1;
``` 

Probably an config thing but if anyone sees what it could be please let me know

**Comment by mkozjak** [comment]
@steveluscher

**Comment by steveluscher** [comment]
Can you throw up a repro repository or Codesandbox? I’ll debug it.

**Comment by basz** [comment]
that would be really appreciated https://github.com/basz/rpc-test

**Comment by NullVoxPopuli** [comment]
exports doesn't exist in the browser. 

Can this be distributed as ESM?

**Comment by steveluscher** [comment]
I tried your repro, and unfortunately couldn't break it.

```shell
sudo n lts  # Install Node LTS
rm pnpm-lock.yaml  # Your lockfile was giving me trouble
pnpm i
pnpm start:dev
```

<img width="727" alt="image" src="https://github.com/elpheria/rpc-websockets/assets/13243/28db83cb-2f83-49c9-962c-224a175cd9d1">

<img width="883" alt="image" src="https://github.com/elpheria/rpc-websockets/assets/13243/933fa45d-cf2e-4b56-a21d-55bf8b2401f2">

**Comment by basz** [comment]
Sorry I wasn’t clear. Now change ***@***.***/package.json to  "rpc-websockets": "7.11.0"On 1 Jun 2024, at 08:14, Steven Luscher ***@***.***> wrote:﻿
I tried your repro, and unfortunately couldn't break it.
sudo n lts  # Install Node LTS
rm pnpm-lock.yaml  # Your lockfile was giving me trouble
pnpm i
pnpm start:dev
image.png (view on web)
image.png (view on web)

**Comment by steveluscher** [comment]
The solution was the most annoying thing possible.

Rename everything to `.cjs`.

#161.
