### ISSUE TITLE
How to correctly handle UnhandledPromiseRejectionWarning?

### ISSUE THREAD

**Issue by clarktlaugh** [elpheria/rpc-websockets#39]
I have a method registered that looks like this:

```
_server.register('delete', function(parameters) {
    const { path, headers } = parameters
    return mylibrary.delete(path, headers).catch((e) => {
        const newError = _mapErrorToRestError(e)
        throw newError
    })
})
```

When there is an error and the `throw` executes, I get the following in the console:
```
(node:2212620) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (C:\Users\laughlcl\source\zookeeper\node_modules\rpc-websockets\node_modules\ws\lib\websocket.js:314:19)
    at Server._callee$ (C:\Users\laughlcl\source\zookeeper\node_modules\rpc-websockets\dist\lib\server.js:667:77)
    at tryCatch (C:\Users\laughlcl\source\zookeeper\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\laughlcl\source\zookeeper\node_modules\regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\laughlcl\source\zookeeper\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\laughlcl\source\zookeeper\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\laughlcl\source\zookeeper\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
```

What I am attempting to do is throw an error that the client code can receive and handle.  This is working properly as far as I can tell.  But, in my server code, I'm getting that console output.  Is there something else I need to do to throw an error for the client?

**Comment by clarktlaugh** [comment]
I'm sorry - I just figured out what the problem is.   This is received when trying to perform about 8 operations, and the first one fails.  After the client receives an error, it disconnects the websocket, and I'm assuming that the server is still trying to send the errors back but the socket is already disconnected.
